USE [IGTI]
-- Tabela Pedido
CREATE TABLE PEDIDO
(
	NUM_PEDIDO			INT			NOT NULL
,	COD_CLIENTE			INT			NOT NULL --FK
,	DAT_PEDIDO			DATETIME	NOT NULL
,	VLR_TOTAL_PEDIDO	NUMERIC		(10,2) NULL
,	COD_FORMA_PAGAMENTO INT			NOT NULL -- FK
)

-- Tabela de cliente
CREATE TABLE CLIENTE
(
	COD_CLIENTE		INT				NOT NULL -- PK
,	NOM_CLIENTE		VARCHAR(100)	NOT NULL
,	DAT_PEDIDO		DATETIME		NOT NULL
,	NUM_CPF_CNPJ	NUMERIC(15)		NULL
,	DSC_ENDER_COBR	VARCHAR(1000)	NOT NULL
,	NUM_TELEFONE	NUMERIC(14)		NOT NULL
)

-- Tabela Forma de Pagamento
CREATE TABLE FORMA_PAGAMENTO
(
	COD_FORMA_PAGAMENTO INT				NOT NULL --PK
,	DSC_FORMA_PAGAMENTO	VARCHAR(100)	NOT NULL
)

-- Tabela Item do Pedido
CREATE TABLE ITEM_PEDIDO
(
	NUM_PEDIDO		INT			NOT NULL --FK
,	COD_ITEM_PEDIDO	INT			NOT NULL --PK
,	COD_SERVICO		INT			NOT NULL --FK
,	QTD_SERVICO		NUMERIC		(2) NOT NULL
,	VLR_TOTAL_ITEM	NUMERIC		(10,2) NOT NULL
)

-- Tabela Servico
CREATE TABLE SERVICO
(
	COD_SERVICO		INT				NOT NULL --PK
,	COD_FORNECEDOR	INT				NOT NULL --FK
,	DSC_SERVICO		VARCHAR(500)	NOT NULL
,	TIP_SERVICO		VARCHAR(50)		NOT NULL
,	VLR_SERVICO		NUMERIC(10,2)	NOT NULL
)

-- Tabela de fornecedores
CREATE TABLE FORNECEDOR
(
	COD_FORNECEDOR	INT				NOT NULL --PK
,	NUM_FORNECEDOR	VARCHAR(100)	NOT NULL
,	NUM_CNPJ		NUMERIC(15)		NULL
,	DSC_ENDERECO	VARCHAR(1000)	NOT NULL
,	NUM_TELEFONE	NUMERIC(14)		NOT NULL
)

-- Definindo a chaves primarias
ALTER TABLE PEDIDO			ADD CONSTRAINT PK_NUMPED PRIMARY KEY (NUM_PEDIDO)
ALTER TABLE CLIENTE			ADD CONSTRAINT PK_CODCLI PRIMARY KEY (COD_CLIENTE)
ALTER TABLE FORMA_PAGAMENTO	ADD CONSTRAINT PK_FORPGT PRIMARY KEY (COD_FORMA_PAGAMENTO)
ALTER TABLE ITEM_PEDIDO		ADD CONSTRAINT PK_ITEPED PRIMARY KEY (COD_ITEM_PEDIDO)
ALTER TABLE SERVICO			ADD CONSTRAINT PK_SERVIC PRIMARY KEY (COD_SERVICO)
ALTER TABLE FORNECEDOR		ADD CONSTRAINT PK_FORNEC PRIMARY KEY (COD_FORNECEDOR)

-- Definindo chaves estrangeiras
--Pedido (N) x (1) Cliente 
ALTER TABLE PEDIDO ADD CONSTRAINT FK_CODCLI FOREIGN KEY (COD_CLIENTE)
REFERENCES	CLIENTE (COD_CLIENTE)

--Pedido (N) x (1) Forma de Pagamento
ALTER TABLE PEDIDO ADD CONSTRAINT FK_FORPGT FOREIGN KEY (COD_FORMA_PAGAMENTO)
REFERENCES	FORMA_PAGAMENTO (COD_FORMA_PAGAMENTO)

--Há uma relação de NxN entre Pedido e Servico por isso foi criada a tabela ITEM_PEDIDO
--Item Pedido (N) x (1) Pedido
ALTER TABLE ITEM_PEDIDO ADD CONSTRAINT FK_NUMPED FOREIGN KEY (NUM_PEDIDO)
REFERENCES	PEDIDO (NUM_PEDIDO)

--Item Pedido (N) x (1) Servico
ALTER TABLE ITEM_PEDIDO ADD CONSTRAINT FK_SERVIC FOREIGN KEY (COD_SERVICO)
REFERENCES	SERVICO (COD_SERVICO)

--Servico (N) x (1) Fornecedor
ALTER TABLE SERVICO ADD CONSTRAINT FK_FORNEC FOREIGN KEY (COD_FORNECEDOR)
REFERENCES	FORNECEDOR (COD_FORNECEDOR)

